library ***numpy*** digunakan untuk mengelola komputasi matrix

pada code di bawah numpy diinisialisasikan dengan *np*. Jadi pada saat ingin memanggil library numpy, kita cukup menulis *np* saja

library ***matplotlib*** digunakan untuk presentasi data berupa grafik (plot)

library ***pandas*** digunakan untuk mengambil/mengimport data dari sumber luar. Misalkan kita ingin mengimport file .csv, excel, .txt kita bisa gunakan library *pandas*

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

***dataset*** merupakan variabel baru yang digunakan untuk membaca Data02.csv

Data yang ada pada excel, akan dibagi kedalam 2 buah variabel (x dan y).
Dimana untuk Country, Age, Salary akan dimasukkan ke dalam variabel x (atribut regulernya).
Kemudian variabel *y* untuk menampung label nya/class nya.

x = dataset.iloc[:, :-1].values Digunakan untuk memanggil semua data yang berada pada variabel x (Country, Age, Salary) kecuali Purchased (variabel y).

In [5]:
dataset = pd.read_csv('Data02.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print(x), digunakan untuk menampilkan data yang berada pada variabel x.
*nan* adalah tampilan jika data kosong (null)

In [6]:
print(x)

[['Semarang' 44.0 72000.0]
 ['Jepara' 27.0 48000.0]
 ['Solo' 30.0 54000.0]
 ['Jepara' 38.0 61000.0]
 ['Solo' 40.0 nan]
 ['Semarang' 35.0 58000.0]
 ['Jepara' nan 52000.0]
 ['Semarang' 48.0 79000.0]
 ['Salatiga' 50.0 83000.0]
 ['Semarang' 37.0 67000.0]]


print(y)
kita gunakan untuk cek apakah data sama dengan yang ada pada file .csv

In [7]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Setelah kita berhasil mengimport dataset, kita akan menghilangkan missing value (nan) dengan cara kita mengganti dengan rata-rata kolomnya
caranya :
function simple imputer
kita gunakan library ***sklearn***.

Kita mendeskripsikan bahwa variabel missing_values adalah data yang ada pada numpay(np), untuk mendeteksi nan, dengan strategi *mean* (nilai rata-rata).
Lalu kita *fit*-kan, dan kita overwrite variabel x
fit(x[:, 1:3])
x kita ambil semua recordnya, kemudian ambil dari kolom pertama sampai yang ketiga.
Lalu kita transform-kan

In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

kita cek kembali pada variabel x, apakah sudah berubah.

In [9]:
print(x)

[['Semarang' 44.0 72000.0]
 ['Jepara' 27.0 48000.0]
 ['Solo' 30.0 54000.0]
 ['Jepara' 38.0 61000.0]
 ['Solo' 40.0 63777.77777777778]
 ['Semarang' 35.0 58000.0]
 ['Jepara' 38.77777777777778 52000.0]
 ['Semarang' 48.0 79000.0]
 ['Salatiga' 50.0 83000.0]
 ['Semarang' 37.0 67000.0]]


kita panggil function ***ColumnTransformer*** dari library *sklearn* dalam folder compose.
kita panggil function ***OneHotEncoder*** untuk mengkodingkan dalam bentuk matrix (dari nominal ke matrix), di dalam library sklearn, folder preprocessing.

Kemudian kita panggil function ColumnTransformer (dengan inisial ct), untuk encodernya menggunakan OneHotEncoder, dengan remainder passthrough.

Kemudian kita ubah formatnya ke dalam array, menggunakan library numpay, lalu kita fit transform


In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

kita cek, apakah nilainya sudah berubah menjadi matrix orde 4. Jika kita ingin merubah nilainya menjadi orde 5, kita tinggal run lagi coding diatas, lalu kita cetak lagi hasilnya print(x), dst.

In [11]:
print(x)

[[0.0 0.0 1.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 0.0 27.0 48000.0]
 [0.0 0.0 0.0 1.0 30.0 54000.0]
 [1.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 0.0 0.0 1.0 40.0 63777.77777777778]
 [0.0 0.0 1.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 0.0 38.77777777777778 52000.0]
 [0.0 0.0 1.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 0.0 37.0 67000.0]]


Setelah kita meng-encode data kategori/atributnya, langkah selanjutnya kita encode labelnya (yes, & no) kita ubah ke bentuk numerik.
Yaitu :
No, kita ubah ke 0
Yes, kita ubah ke 1
menggunakan function labelEncoder dari sklearn

kita buat variabel baru le(LabelEncoder)
lalu kita masukkan ke dalam variabel y kembali (kita timpa), yang sebelumnya No,Yes,No, Yes menjadi nilai 0,1,0,1

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

lalu kita cek apakah variabel y sudah berubah nilainya

In [13]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


membagi dataset menjadi data training, dan data testing

kita panggil function *train_test_split *di dalam library sklearn, kemudian model_selection

masukkan yang atribut regulernya untuk training kita masukkan ke *x_train*, kemudian yang testing kita masukkan ke *x_test* 

kemudian yang labelnya
y_train, dan y_test

kita pisahkan dengan function *train_test_split *. Kita pisahkan antara atribut reguler (x) dan atribut label (y).
kitabuat test_size menjadi 0.2 
maksudnya adalah kita buat pembagiannya data testing nya 20%, data training nya 80%.

Kemudian random_state=1 untuk merandom mengambil 80% dari 10 record disimpan kedalam variabel x_train

In [20]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

kita cek x_train

In [21]:
print(x_train)

[[1.0 0.0 0.0 0.0 38.77777777777778 52000.0]
 [0.0 0.0 0.0 1.0 40.0 63777.77777777778]
 [0.0 0.0 1.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 0.0 38.0 61000.0]
 [1.0 0.0 0.0 0.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 0.0 35.0 58000.0]]


kita panggil x_test, maka akan menampilkan 2 data saja sesuai dengan pembagian data pada perintah sebelumnya 0.2 / 20% dari 10 record

In [22]:
print(x_test)

[[0.0 0.0 0.0 1.0 30.0 54000.0]
 [0.0 0.0 1.0 0.0 37.0 67000.0]]


kita cek y_train. akan menampilkan 8 data

In [23]:
print(y_train)

[0 1 0 0 1 1 0 1]


kita jalankan y_test maka akan menampilkan 2 data, karena hanya mengambil 20% dari 10 record

In [24]:
print(y_test)

[0 1]


 karena kita masih mengalami satu kendala, bahwa untuk skala dari umur dengan skala untuk salary terlalu besar. Oleh karena itu untuk komputasinya di dalam pengolahan data nanti, kita sebaiknya menggunakan skala menggunakan fitur scale

Kita bisa menggunakan StandardScale, MinMaxScale, atau robahScaler

Disini kita akan coba menggunakan standardScaler


kita panggil standardScaler dari sklearn di dalam preprocessing

kemudian kita panggil sc = StandardScaler

yang akan kita scaling hanya pada bagian x_train dan x_test, karena jarak antara age dan salary terlalu besar

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 4:] = sc.fit_transform(x_train[:, 4:])
x_test[:, 4:] = sc.transform(x_test[:, 4:])

kita panggil *x_train* yang baru

In [26]:
print(x_train)

[[1.0 0.0 0.0 0.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 0.0 0.0 1.0 -0.014117293757057777 -0.07013167641635372]
 [0.0 0.0 1.0 0.0 0.566708506533324 0.633562432710455]
 [1.0 0.0 0.0 0.0 -0.30453019390224867 -0.30786617274297867]
 [1.0 0.0 0.0 0.0 -1.9018011447007988 -1.420463615551582]
 [0.0 0.0 1.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 0.0 1.4379472069688968 1.5749910381638885]
 [0.0 0.0 1.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [27]:
print(x_test)

[[0.0 0.0 0.0 1.0 -1.4661817944830124 -0.9069571034860727]
 [0.0 0.0 1.0 0.0 -0.44973664397484414 0.2056403393225306]]
